In [2]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/ba/39/994c4f7e9c59d3ca534a831d18442ac4c529865db20aeaa4fd94e2af5efd/mysql_connector_python-9.6.0-cp312-cp312-win_amd64.whl.metadata
  Downloading mysql_connector_python-9.6.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp312-cp312-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.5 MB 656.4 kB/s eta 0:00:26
   ---------------------------------------- 0.1/16.5 MB 819.2 kB/s eta 0:00:21
   ---------------------------------------- 0.1/16.5 MB 901.1 kB/s eta 0:00:19
   ---------------------------------------- 0.2/16.5 MB 908.0 kB/s eta 0:00:18
   ---------------------------------------- 0.2/16.5 MB 731.4 kB/s eta 0:00:23
    --------------------------------------- 0.2/16.5 MB 798.9 kB/s eta 0:00:21
    --------------------------------------- 0.3/16.5 MB 863.3 kB/s eta 0:00:19
    --------------------------------------- 0.4/16.5 MB 855.4 kB/s eta 0:00:19
    --------------------------------------- 0.4/16.5 MB 865.0 kB/s eta 0:00:19
   - -------------------------------------- 0.5/16.5 MB 907.9 kB/s eta 0:00:18
   - -------------------------------------- 0.5/16.5 MB 885.4 kB/s eta 0:00:19
   - -------------------------------------- 0.5/16.5 MB 927.6 kB/s eta 0:00:18
   - -------------------------------------- 0.6/16.5 MB 942.5 kB/s eta 0:00:17
   - -------------------------------------- 0.6/16.5 MB 942.5 kB/s eta 0:00:17
   - -------------------------------------- 0.6/16.5 MB 942.5 kB/s eta 0:00:17
   - -------------------------------------- 0.7/16.5 MB 882.3 kB/s eta 0:00:18
   - -------------------------------------- 0.7/16.5 MB 890.4 kB/s eta 0:00:18
   - -------------------------------------- 0.8/16.5 MB 910.0 kB/s eta 0:00:18
   -- ------------------------------------- 0.8/16.5 MB 919.4 kB/s eta 0:00:18
   -- ------------------------------------- 0.9/16.5 MB 945.6 kB/s eta 0:00:17
   -- ------------------------------------- 1.0/16.5 MB 947.4 kB/s eta 0:00:17
   -- ------------------------------------- 1.0/16.5 MB 987.8 kB/s eta 0:00:16
   -- ------------------------------------- 1.1/16.5 MB 1.0 MB/s eta 0:00:16
   -- ------------------------------------- 1.2/16.5 MB 1.0 MB/s eta 0:00:15
   --- ------------------------------------ 1.3/16.5 MB 1.1 MB/s eta 0:00:15
   --- ------------------------------------ 1.3/16.5 MB 1.1 MB/s eta 0:00:15
   --- ------------------------------------ 1.5/16.5 MB 1.1 MB/s eta 0:00:14
   --- ------------------------------------ 1.5/16.5 MB 1.1 MB/s eta 0:00:14
   --- ------------------------------------ 1.6/16.5 MB 1.2 MB/s eta 0:00:13
   ---- ----------------------------------- 1.7/16.5 MB 1.2 MB/s eta 0:00:13
   ---- ----------------------------------- 1.8/16.5 MB 1.2 MB/s eta 0:00:13
   ---- ----------------------------------- 1.9/16.5 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 2.0/16.5 MB 1.3 MB/s eta 0:00:12
   ---- ----------------------------------- 2.1/16.5 MB 1.3 MB/s eta 0:00:12
   ----- ---------------------------------- 2.1/16.5 MB 1.3 MB/s eta 0:00:12
   ----- ---------------------------------- 2.2/16.5 MB 1.3 MB/s eta 0:00:12
   ----- ---------------------------------- 2.3/16.5 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.4/16.5 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.4/16.5 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.5/16.5 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.6/16.5 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.7/16.5 MB 1.4 MB/s eta 0:00:11
   ------ --------------------------------- 2.8/16.5 MB 1.4 MB/s eta 0:00:11
   ------ --------------------------------- 2.8/16.5 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/16.5 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 3.0/16.5 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 3.1/16.5 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 3.2/16.5 MB 1.4 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/16.5 MB 1.4 MB/s eta 0:00:10
   -------- ------------------------------- 3.4/16.5 MB 1.5 MB/s eta 0:00:10
   -------- ------------------------------- 3.6/16.5 MB 1.5 MB/s eta 0:00:09
   -------- ------------------------------- 3.6/16.5 MB 1.5 MB/s eta 0:00:09
   -------- ------------------------------- 3.7/16.5 MB 1.5 MB/s eta 0:00:09
   --------- ------------------------------ 3.7/16.5 MB 1.5 MB/s eta 0:00:09
   --------- ------------------------------ 3.8/16.5 MB 1.5 MB/s eta 0:00:09
   --------- ------------------------------ 3.9/16.5 MB 1.5 MB/s eta 0:00:09
   --------- ------------------------------ 3.9/16.5 MB 1.5 MB/s eta 0:00:09
   --------- ------------------------------ 4.0/16.5 MB 1.5 MB/s eta 0:00:09
   --------- ------------------------------ 4.1/16.5 MB 1.5 MB/s eta 0:00:09
   ---------- ----------------------------- 4.2/16.5 MB 1.5 MB/s eta 0:00:09
   ---------- ----------------------------- 4.4/16.5 MB 1.5 MB/s eta 0:00:08
   ---------- ----------------------------- 4.5/16.5 MB 1.5 MB/s eta 0:00:08
   ----------- ---------------------------- 4.6/16.5 MB 1.6 MB/s eta 0:00:08
   ----------- ---------------------------- 4.7/16.5 MB 1.6 MB/s eta 0:00:08
   ----------- ---------------------------- 4.9/16.5 MB 1.6 MB/s eta 0:00:08
   ------------ --------------------------- 5.0/16.5 MB 1.6 MB/s eta 0:00:08
   ------------ --------------------------- 5.1/16.5 MB 1.6 MB/s eta 0:00:08
   ------------ --------------------------- 5.2/16.5 MB 1.6 MB/s eta 0:00:07
   ------------ --------------------------- 5.3/16.5 MB 1.6 MB/s eta 0:00:07
   ------------- -------------------------- 5.5/16.5 MB 1.7 MB/s eta 0:00:07
   ------------- -------------------------- 5.6/16.5 MB 1.7 MB/s eta 0:00:07
   ------------- -------------------------- 5.7/16.5 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 5.9/16.5 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 6.0/16.5 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 6.1/16.5 MB 1.7 MB/s eta 0:00:06
   --------------- ------------------------ 6.2/16.5 MB 1.8 MB/s eta 0:00:06
   --------------- ------------------------ 6.4/16.5 MB 1.8 MB/s eta 0:00:06
   --------------- ------------------------ 6.5/16.5 MB 1.8 MB/s eta 0:00:06
   ---------------- ----------------------- 6.6/16.5 MB 1.8 MB/s eta 0:00:06
   ---------------- ----------------------- 6.8/16.5 MB 1.8 MB/s eta 0:00:06
   ---------------- ----------------------- 6.9/16.5 MB 1.8 MB/s eta 0:00:06
   ---------------- ----------------------- 7.0/16.5 MB 1.8 MB/s eta 0:00:06
   ----------------- ---------------------- 7.1/16.5 MB 1.8 MB/s eta 0:00:06
   ----------------- ---------------------- 7.3/16.5 MB 1.9 MB/s eta 0:00:05
   ----------------- ---------------------- 7.4/16.5 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 7.5/16.5 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 7.7/16.5 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 7.7/16.5 MB 1.9 MB/s eta 0:00:05
   ------------------- -------------------- 7.9/16.5 MB 1.9 MB/s eta 0:00:05
   ------------------- -------------------- 8.0/16.5 MB 1.9 MB/s eta 0:00:05
   ------------------- -------------------- 8.1/16.5 MB 1.9 MB/s eta 0:00:05
   -------------------- ------------------- 8.3/16.5 MB 1.9 MB/s eta 0:00:05
   -------------------- ------------------- 8.4/16.5 MB 1.9 MB/s eta 0:00:05
   -------------------- ------------------- 8.6/16.5 MB 1.9 MB/s eta 0:00:05
   -------------------- ------------------- 8.6/16.5 MB 2.0 MB/s eta 0:00:05
   --------------------- ------------------ 8.7/16.5 MB 1.9 MB/s eta 0:00:04
   --------------------- ------------------ 8.9/16.5 MB 2.0 MB/s eta 0:00:04
   --------------------- ------------------ 8.9/16.5 MB 2.0 MB/s eta 0:00:04
   --------------------- ------------------ 9.0/16.5 MB 2.0 MB/s eta 0:00:04
   --------------------- ------------------ 9.1/16.5 MB 1.9 MB/s eta 0:00:04
   ---------------------- ----------------- 9.2/16.5 MB 2.0 MB/s eta 0:00:04
   ---------------------- ----------------- 9.3/16.5 MB 1.9 MB/s eta 0:00:04
   ---------------------- ----------------- 9.4/16.5 MB 2.0 MB/s eta 0:00:04
   ---------------------- ----------------- 9.5/16.5 MB 2.0 MB/s eta 0:00:04
   ----------------------- ---------------- 9.6/16.5 MB 2.0 MB/s eta 0:00:04
   ----------------------- ---------------- 9.7/16.5 MB 2.0 MB/s eta 0:00:04
   ----------------------- ---------------- 9.8/16.5 MB 2.0 MB/s eta 0:00:04
   ----------------------- ---------------- 9.9/16.5 MB 2.0 MB/s eta 0:00:04
   ------------------------ --------------- 10.0/16.5 MB 2.0 MB/s eta 0:00:04
   ------------------------ --------------- 10.1/16.5 MB 2.0 MB/s eta 0:00:04
   ------------------------ --------------- 10.2/16.5 MB 2.0 MB/s eta 0:00:04
   ------------------------ --------------- 10.3/16.5 MB 2.0 MB/s eta 0:00:04
   ------------------------- -------------- 10.4/16.5 MB 2.0 MB/s eta 0:00:04
   ------------------------- -------------- 10.5/16.5 MB 2.1 MB/s eta 0:00:03
   ------------------------- -------------- 10.6/16.5 MB 2.1 MB/s eta 0:00:03
   ------------------------- -------------- 10.7/16.5 MB 2.1 MB/s eta 0:00:03
   -------------------------- ------------- 10.8/16.5 MB 2.1 MB/s eta 0:00:03
   -------------------------- ------------- 10.9/16.5 MB 2.2 MB/s eta 0:00:03
   -------------------------- ------------- 11.0/16.5 MB 2.2 MB/s eta 0:00:03
   -------------------------- ------------- 11.1/16.5 MB 2.2 MB/s eta 0:00:03
   --------------------------- ------------ 11.2/16.5 MB 2.2 MB/s eta 0:00:03
   --------------------------- ------------ 11.3/16.5 MB 2.2 MB/s eta 0:00:03
   --------------------------- ------------ 11.4/16.5 MB 2.2 MB/s eta 0:00:03
   --------------------------- ------------ 11.5/16.5 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.6/16.5 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.7/16.5 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.8/16.5 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.9/16.5 MB 2.3 MB/s eta 0:00:03
   ----------------------------- ---------- 12.0/16.5 MB 2.2 MB/s eta 0:00:03
   ----------------------------- ---------- 12.1/16.5 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 12.1/16.5 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 12.2/16.5 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 12.3/16.5 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 12.4/16.5 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 12.4/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 12.6/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 12.6/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 12.7/16.5 MB 2.3 MB/s eta 0:00:02
   ------------------------------- -------- 12.8/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 12.9/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 13.0/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 13.0/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 13.1/16.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 13.2/16.5 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 13.3/16.5 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 13.3/16.5 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 13.4/16.5 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 13.5/16.5 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 13.6/16.5 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 13.7/16.5 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 13.8/16.5 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 13.9/16.5 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 14.0/16.5 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 14.1/16.5 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 14.2/16.5 MB 2.3 MB/s eta 0:00:02
   ---------------------------------- ----- 14.2/16.5 MB 2.3 MB/s eta 0:00:02
   ---------------------------------- ----- 14.3/16.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 14.4/16.5 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 14.5/16.5 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.6/16.5 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.6/16.5 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.7/16.5 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.7/16.5 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.8/16.5 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 14.9/16.5 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 14.9/16.5 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 15.0/16.5 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 15.1/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 15.1/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 15.2/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 15.2/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.3/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.3/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.4/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.6/16.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.6/16.5 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 15.8/16.5 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 15.9/16.5 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 15.9/16.5 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 16.0/16.5 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 16.0/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  16.1/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  16.2/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  16.3/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  16.4/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  16.4/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  16.5/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  16.5/16.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 1.9 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
fact_sales=pd.read_csv(r"D:\JN\fact_sales_new.csv")
display("fact_sales",fact_sales)

'fact_sales'

    transaction_id  customer_id  product_id  quantity transaction_date
0                1            1           3         1       2024-05-27
1                1            1          11         2       2024-05-27
2                2            4           9         3       2024-05-25
3                2            4           4         3       2024-05-25
4                2            4           2         1       2024-05-25
..             ...          ...         ...       ...              ...
94              38           16           2         3       2024-04-02
95              39            2          14         1       2024-03-25
96              39            2           8         3       2024-03-25
97              40            1           5         2       2024-01-10
98              40            1          11         2       2024-01-10

[99 rows x 5 columns]

In [4]:
customers=pd.read_csv(r"D:\JN\dim_customers_new.csv")
display("customers",customers.head(10))

'customers'

   customer_id customer_name region signup_date
0            1    Customer_1  South  2023-09-19
1            2    Customer_2  South  2023-03-12
2            3    Customer_3  North  2023-01-05
3            4    Customer_4   West  2023-09-13
4            5    Customer_5  South  2023-08-21
5            6    Customer_6   West  2023-05-05
6            7    Customer_7   East  2023-10-25
7            8    Customer_8  South  2023-01-12
8            9    Customer_9   West  2023-05-13
9           10   Customer_10   East  2023-02-07

In [2]:
import pandas as pd
products=pd.read_csv(r"D:\JN\dim_products_new.csv")
display("Products",products)

'Products'

    product_id   product_name       category
0            1          Bread  Personal Care
1            2         Butter  Personal Care
2            3           Milk        Grocery
3            4           Eggs        Grocery
4            5         Cheese        Grocery
5            6        Shampoo  Personal Care
6            7    Conditioner  Personal Care
7            8           Soap        Grocery
8            9     Toothpaste        Grocery
9           10           Rice  Personal Care
10          11    Cooking Oil        Grocery
11          12       Biscuits  Personal Care
12          13  Chocolate Bar        Grocery
13          14            Tea        Grocery
14          15         Coffee  Personal Care

In [103]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Bhanu@123",
    database="retail"
)

query = "SELECT * FROM dim_products_new"
product = pd.read_sql(query, conn)

# Close connection
conn.close()

print(product.head(5))

product.to_csv("dim_products_new1.csv", index=False)

product=pd.read_csv(r"D:\JN\dim_products_new1.csv")
display("dim_products_new1",product.head(3))

   product_id product_name       category  price
0           1        Bread  Personal Care    2.5
1           2       Butter  Personal Care    3.2
2           3         Milk        Grocery    1.8
3           4         Eggs        Grocery    2.9
4           5       Cheese        Grocery    4.5

'dim_products_new1'

   product_id product_name       category  price
0           1        Bread  Personal Care    2.5
1           2       Butter  Personal Care    3.2
2           3         Milk        Grocery    1.8

In [100]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Bhanu@123",
    database="retail"
)

query = "SELECT * FROM dim_customers_new"
customer = pd.read_sql(query, conn)

# Close connection
conn.close()

print(customer.head(5))

customer.to_csv("dim_customers_new1.csv", index=False)

customer=pd.read_csv(r"D:\JN\dim_customers_new1.csv")
display("dim_costmers_new1",customers.head(3))

   customer_id customer_name region signup_date
0            1    Customer_1  South  2023-09-19
1            2    Customer_2  South  2023-03-12
2            3    Customer_3  North  2023-01-05
3            4    Customer_4   West  2023-09-13
4            5    Customer_5  South  2023-08-21

'dim_costmers_new1'

   customer_id customer_name region signup_date
0            1    Customer_1  South  2023-09-19
1            2    Customer_2  South  2023-03-12
2            3    Customer_3  North  2023-01-05

In [99]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Bhanu@123",
    database="retail"
)

query = "SELECT * FROM fact_sales_new"
fact_sale = pd.read_sql(query, conn)

# Close connection
conn.close()

display(fact_sale.head(5))

fact_sale.to_csv("fact_sales_new1.csv", index=False)

fact_sales=pd.read_csv(r"D:\JN\fact_sales_new1.csv")
display("fact_sales_new1",fact_sales.head(3))

,transaction_id,customer_id,product_id,quantity,transaction_date,total_sales
0,1,1,3,1,2024-05-27,2
1,1,1,11,2,2024-05-27,17
2,2,4,9,3,2024-05-25,8
3,2,4,4,3,2024-05-25,9
4,2,4,2,1,2024-05-25,3

'fact_sales_new1'

,transaction_id,customer_id,product_id,quantity,transaction_date,total_sales
0,1,1,3,1,2024-05-27,2
1,1,1,11,2,2024-05-27,17
2,2,4,9,3,2024-05-25,8

In [105]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Bhanu@123",
    database="retail"
)

query = "SELECT * FROM rfm_base_new"
rfm_base_new = pd.read_sql(query, conn)

# Close connection
conn.close()

display(rfm_base_new.head(5))

rfm_base_new.to_csv("rfm_base_new1.csv", index=False)

   customer_id  recency  frequency  monetary
0            1      638          7      58.0
1            4      651          3      20.0
2            7      730          6      38.0
3           11      659          4      43.0
4           20      602          4      40.0

In [106]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Bhanu@123",
    database="retail"
)

query = "SELECT * FROM cohort_analysis_new"
cohort_analysis_new = pd.read_sql(query, conn)

# Close connection
conn.close()

display(cohort_analysis_new.head(5))

cohort_analysis_new.to_csv("cohort_analysis_new1.csv", index=False)

   customer_id cohort_month order_month  cohort_index
0            1      2024-01     2024-05             4
1            1      2024-01     2024-05             4
2            4      2024-05     2024-05             0
3            4      2024-05     2024-05             0
4            4      2024-05     2024-05             0

In [107]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Bhanu@123",
    database="retail"
)

query = "SELECT * FROM transaction_products"
transaction_products = pd.read_sql(query, conn)

# Close connection
conn.close()

display(transaction_products.head(5))

transaction_products.to_csv("transaction_products1.csv", index=False)

   transaction_id product_name
0               1         Milk
1               1  Cooking Oil
2               2   Toothpaste
3               2         Eggs
4               2       Butter

In [112]:
basket = transaction_products.groupby(['transaction_id','product_name'])['product_name'] \
        .count().unstack().fillna(0)

basket = (basket > 0).astype(int)

print(basket.head())

product_name    Biscuits  Bread  Butter  Cheese  Chocolate Bar  Coffee  \
transaction_id
1                      0      0       0       0              0       0
2                      0      0       1       0              0       0
3                      0      0       0       0              0       0
4                      0      0       0       0              0       0
5                      0      1       0       0              0       0

product_name    Conditioner  Cooking Oil  Eggs  Milk  Rice  Shampoo  Soap  \
transaction_id
1                         0            1     0     1     0        0     0
2                         0            0     1     0     0        0     0
3                         0            0     1     0     0        1     0
4                         0            0     0     0     0        0     0
5                         0            1     0     0     0        0     0

product_name    Tea  Toothpaste
transaction_id
1                 0           0
2                 0           1
3                 0           1
4                 1           1
5                 0           0

In [115]:
import warnings
warnings.filterwarnings('ignore')
!pip install mlxtend -qq

In [118]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(
    basket,
    min_support=0.02,
    use_colnames=True
)

print(frequent_itemsets.head(20))

    support                              itemsets
0     0.150                 frozenset({Biscuits})
1     0.175                    frozenset({Bread})
2     0.275                   frozenset({Butter})
3     0.100                   frozenset({Cheese})
4     0.125            frozenset({Chocolate Bar})
5     0.150                   frozenset({Coffee})
6     0.075              frozenset({Conditioner})
7     0.250              frozenset({Cooking Oil})
8     0.150                     frozenset({Eggs})
9     0.225                     frozenset({Milk})
10    0.150                     frozenset({Rice})
11    0.075                  frozenset({Shampoo})
12    0.175                     frozenset({Soap})
13    0.175                      frozenset({Tea})
14    0.225               frozenset({Toothpaste})
15    0.050         frozenset({Butter, Biscuits})
16    0.025  frozenset({Biscuits, Chocolate Bar})
17    0.025         frozenset({Coffee, Biscuits})
18    0.025    frozenset({Biscuits, Conditioner})
19    0.025    frozenset({Cooking Oil, Biscuits})

In [149]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_itemsets,
    metric="lift",
    min_threshold=1
)

rules = rules[['antecedents','consequents','support','confidence','lift']]

display(rules.head())

,antecedents,consequents,support,confidence,lift
0,frozenset({Butter}),frozenset({Biscuits}),0.050,0.181818,1.212121
1,frozenset({Biscuits}),frozenset({Butter}),0.050,0.333333,1.212121
2,frozenset({Biscuits}),frozenset({Chocolate Bar}),0.025,0.166667,1.333333
3,frozenset({Chocolate Bar}),frozenset({Biscuits}),0.025,0.200000,1.333333
4,frozenset({Coffee}),frozenset({Biscuits}),0.025,0.166667,1.111111

In [150]:
rules['antecedents'] = rules['antecedents'].apply(lambda x: ', '.join(list(x)))
rules['consequents'] = rules['consequents'].apply(lambda x: ', '.join(list(x)))

display(rules.head())

     antecedents    consequents  support  confidence      lift
0         Butter       Biscuits    0.050    0.181818  1.212121
1       Biscuits         Butter    0.050    0.333333  1.212121
2       Biscuits  Chocolate Bar    0.025    0.166667  1.333333
3  Chocolate Bar       Biscuits    0.025    0.200000  1.333333
4         Coffee       Biscuits    0.025    0.166667  1.111111

In [151]:
rules.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,support,confidence,lift
108,"Butter, Chocolate Bar",Conditioner,0.025,1.000000,13.333333
113,Conditioner,"Butter, Chocolate Bar",0.025,0.333333,13.333333
71,Conditioner,"Biscuits, Chocolate Bar",0.025,0.333333,13.333333
66,"Biscuits, Chocolate Bar",Conditioner,0.025,1.000000,13.333333
69,Chocolate Bar,"Biscuits, Conditioner",0.025,0.200000,8.000000
68,"Biscuits, Conditioner",Chocolate Bar,0.025,1.000000,8.000000
111,Chocolate Bar,"Butter, Conditioner",0.025,0.200000,8.000000
110,"Butter, Conditioner",Chocolate Bar,0.025,1.000000,8.000000
115,"Butter, Milk",Coffee,0.025,1.000000,6.666667
73,"Rice, Biscuits",Coffee,0.025,1.000000,6.666667

In [152]:
rules.to_csv("market_basket_rules1.csv", index=False)

In [154]:
df15=pd.read_csv(r"D:\JN\market_basket_rules1.csv")
display(df15)

          antecedents       consequents  support  confidence      lift
0              Butter          Biscuits    0.050    0.181818  1.212121
1            Biscuits            Butter    0.050    0.333333  1.212121
2            Biscuits     Chocolate Bar    0.025    0.166667  1.333333
3       Chocolate Bar          Biscuits    0.025    0.200000  1.333333
4              Coffee          Biscuits    0.025    0.166667  1.111111
..                ...               ...      ...         ...       ...
175  Rice, Toothpaste               Tea    0.025    0.500000  2.857143
176   Toothpaste, Tea              Rice    0.025    0.500000  3.333333
177              Rice   Toothpaste, Tea    0.025    0.166667  3.333333
178               Tea  Rice, Toothpaste    0.025    0.142857  2.857143
179        Toothpaste         Rice, Tea    0.025    0.111111  4.444444

[180 rows x 5 columns]

In [142]:
import pandas as pd
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Bhanu@123",
    database="retail"
)

# Load RFM base table
query = "SELECT * FROM rfm_base_new"
rfm1 = pd.read_sql(query, conn)

# Close connection
conn.close()

print("Data Loaded Successfully")
display(rfm1.head())


# -----------------------------
# RFM SCORING (1-5 SCALE)
# -----------------------------

# Recency score (lower recency = better)
rfm1['R_score'] = pd.qcut(rfm1['recency'], 5, labels=[5,4,3,2,1])

# Frequency score (higher frequency = better)
rfm1['F_score'] = pd.qcut(rfm1['frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])

# Monetary score (higher spending = better)
rfm1['M_score'] = pd.qcut(rfm1['monetary'], 5, labels=[1,2,3,4,5])


# Convert scores to integer
rfm1['R_score'] = rfm1['R_score'].astype(int)
rfm1['F_score'] = rfm1['F_score'].astype(int)
rfm1['M_score'] = rfm1['M_score'].astype(int)


# Create RFM Score
rfm1['RFM_score'] = (
    rfm1['R_score'].astype(str) + rfm1['F_score'].astype(str) + rfm1['M_score'].astype(str)
)

display("rfm_score",rfm1.head())



#customer segmentation
def segment_customer(row):

    if row['R_score'] >= 4 and row['F_score'] >= 4:
        return "Champions"

    elif row['R_score'] >= 3 and row['F_score'] >= 3:
        return "Loyal Customers"

    elif row['R_score'] <= 2 and row['F_score'] >= 3:
        return "At Risk"

    else:
        return "Hibernating"


rfm1['Segment'] = rfm1.apply(segment_customer, axis=1)

# Show segment distribution
print("\nCustomer Segments Distribution:")
display(rfm1['Segment'].value_counts())


rfm1.to_csv("rfm_customer_segments_new.csv", index=False)

print("\nRFM Segmentation Completed Successfully")
print("File saved as: rfm_customer_segments_new.csv")

# df5=pd.read_csv(r"C:\Users\Bhanu prasad\Downloads\rfm_customer_segments.csv")
# display(df5)

Data Loaded Successfully

   customer_id  recency  frequency  monetary
0            1      638          7      58.0
1            4      651          3      20.0
2            7      730          6      38.0
3           11      659          4      43.0
4           20      602          4      40.0

'rfm_score'

,customer_id,recency,frequency,monetary,R_score,F_score,M_score,RFM_score
0,1,638,7,58.0,3,5,4,354
1,4,651,3,20.0,3,1,1,311
2,7,730,6,38.0,1,4,2,142
3,11,659,4,43.0,2,2,3,223
4,20,602,4,40.0,5,2,3,523

Customer Segments Distribution:

Segment
Hibernating        8
At Risk            4
Champions          4
Loyal Customers    3
Name: count, dtype: int64

RFM Segmentation Completed Successfully
File saved as: rfm_customer_segments_new.csv